### ISSUE TITLE
displayed mercenary status

### ISSUE THREAD

**Issue by neronrk** [jpw1991/chebs-mercenaries#34]
![roam](https://github.com/jpw1991/chebs-mercenaries/assets/142999382/cf7316e3-7257-473a-9cb3-2ac20f1eb3c7)
![fol](https://github.com/jpw1991/chebs-mercenaries/assets/142999382/f2594bb9-acf2-4f8e-8ba4-e07581765f09)
![wai](https://github.com/jpw1991/chebs-mercenaries/assets/142999382/df89ce90-50dd-4527-88cd-06ab5b753f42)

**Comment by neronrk** [comment]
разобрался, в русском переводе не хватало строчек 33-37 (I figured it out, the Russian translation was missing lines 33-37)
"$chebgonaz_worker_target": "Цель",
    "$chebgonaz_worker_cantfindtarget": "Не могу найти цель.",
    "$chebgonaz_minionstatus_following": "Следует"
	"$chebgonaz_minionstatus_waiting": "Ждет"
	"$chebgonaz_minionstatus_roaming": "Гуляет"

**Comment by jpw1991** [comment]
Thank you

**Comment by jpw1991** [comment]
included in 2.1.2
