### ISSUE TITLE
No Mercs appear, thing not removed from box.

### ISSUE THREAD

**Issue by Rallyrick** [jpw1991/chebs-mercenaries#43]
This mod looks awesome I would really like to use it but the mercs dont appear after putting stuff in the box, this is the error I am getting
[Error  : Unity Log] MissingMethodException: Method not found: int .Inventory.CountItems(string,int)
Stack trace:
ChebsMercenaries.Structure.MercenaryChest.NextMercenary () (at <51584429dd2f43f394079aff8781355f>:0)
ChebsMercenaries.Structure.MercenaryChest+<Recruitment>d__33.MoveNext () (at <51584429dd2f43f394079aff8781355f>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <50b18efe22344b9eb3b7d77b08ea287f>:0)

**Comment by Rallyrick** [comment]
I found the issue. downloaded wrong version from nexus.  Thank you great mod!

**Comment by jpw1991** [comment]
No worries, I'm glad you got it working. Have fun :)
