### ISSUE TITLE
Bug ''NoplayerHPBarNickname'' 

### ISSUE THREAD

**Issue by Simoss22** [jpw1991/chebs-mercenaries#58]
Hello! I noticed a small bug with the mob ''NoplayerHPBarNickname'' All mobs have 2 stars next to their name now and even if it's only normal mobs

**Comment by jpw1991** [comment]
Hello Simoss, I don't think this has anything to do with Cheb's Mercenaries. Please open the issue on the repository for [NoPlayerHPBarNickname](https://github.com/JFHeim/NoPlayerHPBarNickname)
