### ISSUE TITLE
Commandable workers

### ISSUE THREAD

**Issue by Cordain** [jpw1991/chebs-mercenaries#9]
# Description

A woodcutter and miner should have ability to be commanded.
It would be nice if workers could be led to the working area, in case when hired in base.

## Is the feature related to a problem?

It feels weird them doing work when they are not supposed to.

## Solutions

Apply same commands as for warriors.

### Your Ideal Solution

This option may be toggled in the mod config.

**Comment by jpw1991** [comment]
Hi Cordain, thanks for opening the issue I will see if I can do something

**Comment by jpw1991** [comment]
fixed in 1.2.0
